const items=[
['airport-transfers','Airport Transfers','Professional airport pickup and drop-off with punctual chauffeur service, luggage assistance and a smooth transition between your home, office, hotel and terminal.','https://images.unsplash.com/photo-1637177799109-be60d6a40a19?auto=format&fit=crop&w=1600&q=82'],
['vip-transfers','VIP Transfers','Discreet premium transport for VIPs, executives, special guests and high-profile journeys, with comfort, presentation, privacy and security in mind.','https://images.unsplash.com/photo-1780296269675-169390638617?auto=format&fit=crop&w=1600&q=82'],
['weddings','Weddings','Elegant wedding transport for the bride, groom and wedding party, with a beautifully presented vehicle and careful timing for your special day.','https://images.unsplash.com/photo-1764402969196-46e9c6e91ac7?auto=format&fit=crop&w=1600&q=82'],
['corporate-travel','Corporate Travel','Professional chauffeur travel between offices, meetings, airports, hotels and corporate events, designed around demanding schedules.','https://images.unsplash.com/photo-1780296269675-169390638617?auto=format&fit=crop&w=1600&q=82'],
['formal','School Formals','Safe, stylish transport for students attending school formals and graduation celebrations, creating a memorable arrival and a dependable journey home.','https://images.unsplash.com/photo-1768809249126-d5a6230d0d67?auto=format&fit=crop&w=1600&q=82'],
['private-charter','Private Charter','A private chauffeur and luxury vehicle reserved around your itinerary, whether for sightseeing, shopping, appointments or a full day of travel.','https://images.unsplash.com/photo-1771775751121-3091d79073d4?auto=format&fit=crop&w=1600&q=82'],
['events','Events & Occasions','Door-to-door chauffeur transport for concerts, sporting events, dinners, celebrations and special occasions without the parking or driving stress.','https://images.unsplash.com/photo-1766019463317-1cc801c15e61?auto=format&fit=crop&w=1600&q=82'],
['as-directed','As Directed','Keep the chauffeur and vehicle at your disposal and simply give directions as your day unfolds—ideal when plans, stops or timing may change.','https://images.unsplash.com/photo-1729831607236-f4187bf35632?auto=format&fit=crop&w=1600&q=82']
];
export default function Services(){return <main className="innerPage"><section className="innerHero"><p className="goldKicker">OUR SERVICES</p><h1>Professional chauffeur service<br/>for every occasion.</h1><p>Select a service from the homepage to come directly to a large image, a brief explanation and a booking button.</p></section><section className="serviceDetailGrid">{items.map(([id,title,text,image])=><article id={id} key={id} className="serviceDetailCard"><img className="serviceDetailImage" src={image} alt={title}/><div className="detailCopy"><h2>{title}</h2><p>{text}</p><a className="outlineButton" href={`/quote?service=${id}`}>BOOK THIS SERVICE</a></div></article>)}</section></main>}