const items=[
['airport-transfers','Airport Transfers','✈️','Professional airport pickup and drop-off with punctual chauffeur service, luggage assistance and a smooth transition between your home, office, hotel and terminal.'],
['vip-transfers','VIP Transfers','👑','Discreet premium transport for VIPs, executives, special guests and high-profile journeys, with comfort, presentation, privacy and security in mind.'],
['weddings','Weddings','💍','Elegant wedding transport for the bride, groom and wedding party, with a beautifully presented vehicle and careful timing for your special day.'],
['corporate-travel','Corporate Travel','💼','Professional chauffeur travel between offices, meetings, airports, hotels and corporate events, designed around demanding schedules.'],
['formal','School Formals','🎓','Safe, stylish transport for students attending school formals and graduation celebrations, creating a memorable arrival and a dependable journey home.'],
['private-charter','Private Charter','🚘','A private chauffeur and luxury vehicle reserved around your itinerary, whether for sightseeing, shopping, appointments or a full day of travel.'],
['events','Events & Occasions','🎟️','Door-to-door chauffeur transport for concerts, sporting events, dinners, celebrations and special occasions without the parking or driving stress.'],
['as-directed','As Directed','🧭','Keep the chauffeur and vehicle at your disposal and simply give directions as your day unfolds—ideal when plans, stops or timing may change.']
];
export default function Services(){return <main className="innerPage"><section className="innerHero"><p className="goldKicker">OUR SERVICES</p><h1>Professional chauffeur service<br/>for every occasion.</h1><p>Select a service from the homepage to see a concise explanation here, then book when you are ready.</p></section><section className="serviceDetailGrid">{items.map(([id,title,icon,text])=><article id={id} key={id} className="serviceDetailCard"><div className={`servicePhoto servicePhoto-${id}`}><span>{icon}</span></div><div><h2>{title}</h2><p>{text}</p><a className="outlineButton" href={`/quote?service=${id}`}>BOOK THIS SERVICE</a></div></article>)}</section></main>}