'use client';
import { useMemo,useState } from 'react';

export default function QuotePage(){
 const [vehicle,setVehicle]=useState('V-Class'),[km,setKm]=useState(25),[child,setChild]=useState(0),[baby,setBaby]=useState(0),[booster,setBooster]=useState(0),[meet,setMeet]=useState(false),[returnTrip,setReturnTrip]=useState(false);
 const [origin,setOrigin]=useState(''),[destination,setDestination]=useState(''),[date,setDate]=useState(''),[time,setTime]=useState(''),[passengers,setPassengers]=useState(1),[notes,setNotes]=useState('');
 const [liveQuote,setLiveQuote]=useState(null),[quoteStatus,setQuoteStatus]=useState(''),[bookingStatus,setBookingStatus]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[phone,setPhone]=useState('');
 const estimate=useMemo(()=>{const base={'S-Class':105,'V-Class':95,'Audi Q7':100,'Sprinter':145}[vehicle],rate={'S-Class':3.35,'V-Class':3.05,'Audi Q7':3.2,'Sprinter':4.1}[vehicle];let total=Math.max(base,base+Number(km)*rate)+Number(child)*15+Number(baby)*20+Number(booster)*10+(meet?20:0);return returnTrip?total*1.9:total},[vehicle,km,child,baby,booster,meet,returnTrip]);
 async function calculateRoute(){setQuoteStatus('Calculating live route…');setLiveQuote(null);try{const r=await fetch('/api/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origin,destination,vehicle,child,baby,booster,meet,returnTrip})});const d=await r.json();if(!r.ok) throw new Error(d.error);setLiveQuote(d);setKm(d.km);setQuoteStatus(`${d.km} km · approximately ${d.minutes} min`)}catch(e){setQuoteStatus(e.message||'Live route pricing is not available yet.')}}
 async function submitBooking(e){e.preventDefault();setBookingStatus('Sending your request…');try{const r=await fetch('/api/booking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,phone,origin,destination,date,time,passengers,vehicle,child,baby,booster,meet,returnTrip,notes,quotedFare:liveQuote?.fare||Math.round(estimate)})});const d=await r.json();if(!r.ok) throw new Error(d.error);setBookingStatus(`Request received. Reference ${d.reference}. We will confirm availability shortly.`)}catch(e){setBookingStatus(e.message||'Unable to submit your request. Please call us.')}}
 const fare=liveQuote?.fare||Math.round(estimate);
 const mapSrc=origin&&destination?`https://www.google.com/maps?q=${encodeURIComponent(origin+' to '+destination)}&output=embed`:'';
 return <main className="quotePage">
  <header className="quoteHeader"><a href="/" className="luxBrand"><span className="crest">MB</span><span><b>MBLS</b><small>MY BLACK LIMO SERVICE</small></span></a><a href="/">← BACK TO HOME</a></header>
  <section className="quoteIntro"><p className="goldKicker">PRIVATE CHAUFFEUR BOOKING</p><h1>Plan your journey.</h1><p>Enter your trip details for an indicative fare, then send your booking request for confirmation.</p></section>
  <section className="quoteWorkspace">
   <div className="quotePanel">
    <div className="routeFields"><label>FROM<input value={origin} onChange={e=>setOrigin(e.target.value)} placeholder="Pickup location"/></label><label>TO<input value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Destination"/></label><label>DATE<input value={date} onChange={e=>setDate(e.target.value)} type="date"/></label><label>TIME<input value={time} onChange={e=>setTime(e.target.value)} type="time"/></label></div>
    <div className="quoteGrid"><label>VEHICLE<select value={vehicle} onChange={e=>{setVehicle(e.target.value);setLiveQuote(null)}}><option>V-Class</option><option>S-Class</option><option>Audi Q7</option><option>Sprinter</option></select></label><label>PASSENGERS<input type="number" min="1" max="14" value={passengers} onChange={e=>setPassengers(e.target.value)}/></label><label>CHILD SEAT<select value={child} onChange={e=>{setChild(e.target.value);setLiveQuote(null)}}><option value="0">None</option><option value="1">1 (+$15)</option><option value="2">2 (+$30)</option></select></label><label>BABY SEAT<select value={baby} onChange={e=>{setBaby(e.target.value);setLiveQuote(null)}}><option value="0">None</option><option value="1">1 (+$20)</option><option value="2">2 (+$40)</option></select></label><label>BOOSTER<select value={booster} onChange={e=>{setBooster(e.target.value);setLiveQuote(null)}}><option value="0">None</option><option value="1">1 (+$10)</option><option value="2">2 (+$20)</option></select></label></div>
    <div className="toggles"><label><input type="checkbox" checked={meet} onChange={e=>{setMeet(e.target.checked);setLiveQuote(null)}}/> Meet & Greet (+$20)</label><label><input type="checkbox" checked={returnTrip} onChange={e=>{setReturnTrip(e.target.checked);setLiveQuote(null)}}/> Return trip</label></div>
    <div className="quoteActions"><button className="goldButton button" onClick={calculateRoute} disabled={!origin||!destination}>CALCULATE LIVE ROUTE</button>{quoteStatus&&<span className="status">{quoteStatus}</span>}</div>
    <div className="estimate"><span>{liveQuote?'ROUTE-BASED ESTIMATE':'PRELIMINARY ESTIMATE'}</span><strong>${fare} AUD</strong></div>
    <form className="bookingForm quoteBooking" onSubmit={submitBooking}><label>NAME<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></label><label>EMAIL<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>PHONE<input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Mobile number"/></label><label className="fullWidth">NOTES<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Flight number, luggage, special requests or return details"/></label><button className="goldButton button fullWidth" type="submit">SEND BOOKING REQUEST →</button>{bookingStatus&&<p className="status fullWidth">{bookingStatus}</p>}</form>
   </div>
   <aside className="mapPanel"><div><p className="goldKicker">ROUTE VIEW</p><h2>Your journey at a glance.</h2><p>Map preview appears here after you enter pickup and destination details.</p></div>{mapSrc?<iframe title="Journey map" src={mapSrc} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/>:<div className="mapPlaceholder">Enter your pickup and destination to preview the route.</div>}<small>Final fare and chauffeur availability are confirmed by My Black Limo Service.</small></aside>
  </section>
 </main>
}