'use client';
import { useMemo, useState } from 'react';

const fleet=[['Mercedes-Benz S-Class','1–3 passengers','First Class'],['Mercedes-Benz V-Class','1–7 passengers','Business Van'],['Audi Q7','1–5 passengers','Luxury SUV'],['Mercedes Sprinter','Groups & events','Premium Group']];
const services=[['Airport Transfers','Flight-aware pickups, meet & greet and discreet assistance.'],['Corporate Chauffeur','Executive transport designed around demanding schedules.'],['VIP & Private','Confidential, polished transport for guests who expect more.'],['Weddings & Events','Immaculate vehicles and coordinated arrivals for important occasions.'],['Hourly Chauffeur','A private driver and vehicle at your disposal.'],['Sydney & NSW','Bespoke transfers, roadshows and private touring.']];
export default function Home(){
 const [vehicle,setVehicle]=useState('V-Class'); const [km,setKm]=useState(25); const [seats,setSeats]=useState(0); const [baby,setBaby]=useState(0);
 const quote=useMemo(()=>{const base={"S-Class":95,"V-Class":85,"Audi Q7":90,"Sprinter":135}[vehicle]; const rate={"S-Class":3.2,"V-Class":2.85,"Audi Q7":3,"Sprinter":3.8}[vehicle]; return Math.max(base,base+Number(km)*rate+Number(seats)*15+Number(baby)*20)},[vehicle,km,seats,baby]);
 return <main>
  <header><a className="brand" href="#">MY BLACK <span>LIMO SERVICE</span></a><nav><a href="#services">Services</a><a href="#fleet">Fleet</a><a href="#experience">Experience</a><a href="#contact">Contact</a></nav><a className="call" href="tel:+61420770707">+61 420 770 707</a></header>
  <section className="hero"><div className="shade"/><div className="heroCopy"><p className="eyebrow">SYDNEY · PRIVATE CHAUFFEUR</p><h1>Arrive with<br/><em>distinction.</em></h1><p>Quiet luxury, immaculate vehicles and professional chauffeurs for airport, corporate, VIP and private travel.</p><div className="actions"><a className="primary" href="#quote">GET AN INSTANT QUOTE</a><a href="#fleet">EXPLORE THE FLEET →</a></div></div><div className="heroNote">SYDNEY HARBOUR<br/><span>Available 24 / 7 by reservation</span></div></section>
  <section id="quote" className="quote"><div><p className="eyebrow">PRIVATE TRANSFER</p><h2>Plan your journey</h2><p className="muted">A preliminary fare estimator while live route pricing is being connected.</p></div><div className="quoteGrid"><label>Vehicle<select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option>V-Class</option><option>S-Class</option><option>Audi Q7</option><option>Sprinter</option></select></label><label>Estimated distance (km)<input type="number" min="1" value={km} onChange={e=>setKm(e.target.value)}/></label><label>Child seat<select value={seats} onChange={e=>setSeats(e.target.value)}><option value="0">None</option><option value="1">1 seat</option><option value="2">2 seats</option></select></label><label>Baby seat<select value={baby} onChange={e=>setBaby(e.target.value)}><option value="0">None</option><option value="1">1 seat</option><option value="2">2 seats</option></select></label></div><div className="estimate"><span>PRELIMINARY ESTIMATE</span><strong>${Math.round(quote)} AUD</strong><a href="mailto:info@myblacklimoservice.com">REQUEST BOOKING →</a></div></section>
  <section id="services" className="section"><p className="eyebrow">OUR SERVICES</p><div className="sectionHead"><h2>For every occasion.<br/>Never ordinary.</h2><p>From the first greeting to the final door close, every detail is considered.</p></div><div className="cards">{services.map((s,i)=><article key={s[0]}><span>0{i+1}</span><h3>{s[0]}</h3><p>{s[1]}</p></article>)}</div></section>
  <section id="fleet" className="fleet"><div className="sectionHead"><div><p className="eyebrow">THE FLEET</p><h2>Black. Immaculate.<br/>Unmistakable.</h2></div><p>Mercedes-Benz and Audi vehicles selected for comfort, presence and discretion.</p></div><div className="fleetGrid">{fleet.map((f,i)=><article key={f[0]}><div className={'carPlaceholder car'+i}><span>{f[2]}</span></div><h3>{f[0]}</h3><p>{f[1]}</p></article>)}</div></section>
  <section id="experience" className="experience"><div><p className="eyebrow">THE EXPERIENCE</p><h2>The details<br/><em>matter.</em></h2></div><div className="amenities"><div><b>01</b><h3>Still & sparkling water</h3><p>Complimentary refreshments presented in every vehicle.</p></div><div><b>02</b><h3>Fresh mints</h3><p>A small finishing touch, always within reach.</p></div><div><b>03</b><h3>Quiet by default</h3><p>A calm cabin. Music available when you want it, never imposed.</p></div><div><b>04</b><h3>Professional chauffeurs</h3><p>Discreet, punctual and impeccably presented.</p></div></div></section>
  <section className="cta"><p className="eyebrow">YOUR JOURNEY, ELEVATED</p><h2>Wherever you're going,<br/><em>arrive beautifully.</em></h2><a className="primary" href="#quote">BOOK YOUR CHAUFFEUR</a></section>
  <footer id="contact"><div className="brand">MY BLACK <span>LIMO SERVICE</span></div><div><b>CONTACT</b><a href="tel:+61420770707">+61 420 770 707</a><a href="mailto:info@myblacklimoservice.com">info@myblacklimoservice.com</a></div><div><b>SERVICES</b><span>Airport · Corporate · VIP</span><span>Weddings · Hourly · NSW</span></div><div><b>LEGAL</b><a href="/privacy">Privacy Policy</a><span>ABN 14 106 640 832</span></div><small>© 2026 My Black Limo Service. Sydney, Australia.</small></footer>
 </main>
}