export const metadata={title:'Hourly Chauffeur Rates',description:'Published as-directed hourly chauffeur hire rates for Sydney — Executive Sedan, Executive SUV, V-Class and 11-Seater Sprinter.'};
const TIERS=['2+ hrs','4+ hrs','6+ hrs','8+ hrs'];
const RATES=[
 {name:'Executive Sedan',sub:'Mercedes-Benz S-Class',rates:[130,125,120,115]},
 {name:'Executive SUV',sub:'Audi Q7',rates:[170,160,155,150]},
 {name:'V-Class',sub:'7-Seater People Mover',rates:[200,195,185,180]},
 {name:'11-Seater',sub:'Mercedes-Benz Sprinter',rates:[265,255,245,235]}
];
export default function Pricing(){return <main className="innerPage"><section className="innerHero"><p className="goldKicker">AS-DIRECTED HOURLY HIRE</p><h1>Hourly chauffeur rates.</h1><p>Keep your chauffeur and vehicle at your disposal for as long as you need — ideal for meetings, events, shopping or a day where plans may change. Below are our published as-directed hourly hire rates for Sydney.</p></section><section className="rateTableSection"><div className="rateTableWrap"><table className="rateTable"><thead><tr><th>Vehicle</th>{TIERS.map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{RATES.map(v=><tr key={v.name}><td><b>{v.name}</b><span>{v.sub}</span></td>{v.rates.map((r,i)=><td key={i}>{`$${r}/hr`}</td>)}</tr>)}</tbody></table></div><div className="rateNotes"><h2>Good to know</h2><ul><li>Rates shown are per hour of as-directed hourly hire. Each column is the rate that applies once your booking reaches that minimum duration — for example, the 4+ hrs rate applies to bookings of 4 hours or more.</li><li>Late-night surcharges apply on top of the hourly rate above: <b>10pm–1am +15%</b>, <b>1am–4am +25%</b>, <b>4am–5am +15%</b>.</li><li>These are as-directed hourly rates only. Airport transfers and point-to-point (A to B) trips are priced separately and quoted live via our <a href="/quote">instant quote tool</a>.</li><li>All rates are in AUD. Tolls, parking and unusual waiting time may apply in addition. Confirmed bookings are subject to our <a href="/terms">Terms & Conditions</a>.</li></ul><a className="goldButton" href="/quote">GET AN INSTANT QUOTE →</a></div></section></main>}
